import { useRef } from 'react';
import { Tab } from '@headlessui/react';
import { GetStaticProps } from 'next';
import classNames from 'classnames';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Masonry from 'react-masonry-css';

import { createApi } from 'unsplash-js';
import nodeFetch from 'node-fetch';

import type { LightGallery } from 'lightgallery/lightgallery';
import LightGalleryComponent from 'lightgallery/react';

import 'lightgallery/css/lg-thumbnail.css';
import 'lightgallery/css/lg-zoom.css';
import 'lightgallery/css/lightgallery.css';

// plugins
import lgThumbnail from 'lightgallery/plugins/thumbnail';
import lgZoom from 'lightgallery/plugins/zoom';

import bgModern from '../public/bgModern.jpg';

type Photo = {
  src: string,
  thumb: string,
  width: number,
  height: number,
  alt: string,
}

const tabs = [
  {
    key: 'all',
    display: 'All',
  },
  {
    key: 'oceans',
    display: 'Oceans',
  },
  {
    key: 'forests',
    display: 'Forests',
  },
]

type HomeProps = {
  oceans: Photo[],
  forests: Photo[],
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {

  const unsplash = createApi({
    accessKey: process.env.UNSPLASH_ACCESS_KEY!,
    fetch: nodeFetch as unknown as typeof fetch,
  })  
  const oceans = await unsplash.search.getPhotos({
    query: 'oceans',
  })

  const forests = await unsplash.search.getPhotos({
    query: 'forests',
  })

  const mapOceans: Photo[] = []

  if(oceans.type === 'success') {
    const oceanArr = oceans.response.results.map((ocean, i) => ({
        src: ocean.urls.full,
        thumb: ocean.urls.thumb,
        width: ocean.width,
        height: ocean.height,
        alt: ocean.alt_description ?? `ocean-img-${i}`,
      }))
      mapOceans.push(...oceanArr)
  } else {
    console.error('ERROR: Could not get ocean photo');
  }

  const mapForest: Photo[] = []

  if(forests.type === 'success') {
    const forestArr = forests.response.results.map((forest, i) => ({
        src: forest.urls.full,
        thumb: forest.urls.thumb,
        width: forest.width,
        height: forest.height,
        alt: forest.alt_description ?? `forest-img-${i}`,
      }))
      mapForest.push(...forestArr)
  } else {
    console.error('ERROR: Could not get forest photo');
  }

  return ({
    props: {
      oceans: mapOceans,
      forests: mapForest,
  }
})
}

export default function Home({oceans, forests}: HomeProps) {
  return (
    <div className="h-full overflow-auto">
      <Head>
        <title>Nature Canvas</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Image src={bgModern} alt='background-img' className='fixed top-0 left-0 z-0' placeholder='blur'/>
      <div className='fixed top-0 left-0 w-full h-full from-zinc-900 bg-gradient-to-t z-10'></div>

      <header className='fixed top-0 w-full z-30 flex justify-between items-center h-[90px] px-20 from-zinc-900 bg-gradient-to-b'>
        <span className='uppercase text-lg font-medium'>Nature Canvas</span>
        <Link href='#' className='rounded-3xl bg-white text-stone-700 px-6 py-2 hover:underline decoration-gray-400  hover:bg-opacity-90 '>
            Contact
        </Link>
      </header>
      <main className='relative pt-[120px] z-20'>
        <div className="flex flex-col items-center h-full">

      <Tab.Group>
      <Tab.List className='flex items-center gap-16'>
        {tabs.map(tab => (
        <Tab key={tab.key} className='p-2 uppercase'>
          {({selected}) => (<span className={classNames("uppercase text-lg", selected ? 'text-white' : 'text-stone-600')}>{tab.display}</span>)}
        </Tab>
        ))}
      </Tab.List>
      <Tab.Panels className='h-full max-w-[900px] w-full p-2 sm:p-4 my-6'>
        <Tab.Panel className='overflow-auto'>
          <Gallery photos={[...oceans, ...forests]}/>
        </Tab.Panel>
        <Tab.Panel>
          <Gallery photos={oceans}/>
        </Tab.Panel>
        <Tab.Panel>
          <Gallery photos={forests}/>
        </Tab.Panel>
      </Tab.Panels>
    </Tab.Group>

        </div>
      </main>
      <footer className='relative h-[60px] flex justify-center items-center py-2 sm:py-12 uppercase font-medium z-20'>
        <p>Nature Canvas</p>
      </footer>
    </div>
  );
}

type GalleryProps = {
  photos: Photo[],
}

function Gallery({photos}:GalleryProps) {

  const lightBoxRef = useRef<LightGallery | null>(null)
  return (
    <>
      <Masonry breakpointCols={2} className='flex gap-4' columnClassName=''>
       {photos.map((photo, i) => (
         <Image key={photo.src} src={photo.src} width={photo.width} height={photo.height} alt={photo.alt} className='my-4 rounded-lg hover:opacity-80 cursor-pointer' blurDataURL={"data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoMABAABUB8JbACdABPETEAAP7RkuUo9LhYapfHh8xO0wO5bEY3NoTR5RN0A5XacUeGAA=="} onClick={() =>{
           lightBoxRef.current?.openGallery(i)
         }
        }/>
       ))}
     </Masonry>
     <LightGalleryComponent onInit={ref => {
       if(ref) {
         lightBoxRef.current = ref.instance
       }
     }} speed={500} plugins={[lgThumbnail, lgZoom]} dynamic dynamicEl={photos.map(photo => ({
       src: photo.src,
       thumb: photo.src,
     }))}/> 
    </>
  )
}
